// <auto-generated />
using InformationSystemsDesign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformationSystemsDesign.Migrations
{
    [DbContext(typeof(InformationSystemsDesignContext))]
    [Migration("20221209234333_RecreatedStrRozvKey")]
    partial class RecreatedStrRozvKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InformationSystemsDesign.Models.GLPR", b =>
                {
                    b.Property<string>("CdPr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CdTp")
                        .HasColumnType("int");

                    b.Property<string>("NmPr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdPr");

                    b.HasIndex(new[] { "CdTp" }, "IX_GLPR_CdTp");

                    b.ToTable("GLPR", (string)null);
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.Spec", b =>
                {
                    b.Property<string>("CdSb")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdKp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QtyKp")
                        .HasColumnType("int");

                    b.HasKey("CdSb", "CdKp");

                    b.HasIndex(new[] { "CdKp" }, "IX_Spec_CdKp");

                    b.ToTable("Spec", null, t =>
                        {
                            t.HasCheckConstraint("CK_Spec_CdKp", "[CdKp] != [CdSb]");

                            t.HasCheckConstraint("CK_Spec_CdSb", "[CdSb] != [CdKp]");

                            t.HasCheckConstraint("CK_Spec_QtyKp", "[QtyKp] >= 0");
                        });
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.StrRozv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdKp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdSb")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdVyr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QtyKp")
                        .HasColumnType("int");

                    b.Property<string>("RivGrf")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("('.1')");

                    b.Property<int>("RivNb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CdKp");

                    b.HasIndex("CdSb");

                    b.HasIndex(new[] { "CdVyr" }, "IX_StrRozv_CdVyr");

                    b.ToTable("StrRozv", (string)null);
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.TypePr", b =>
                {
                    b.Property<int>("CdTp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdTp"));

                    b.Property<string>("NmTp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdTp");

                    b.ToTable("TypePr", (string)null);
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.GLPR", b =>
                {
                    b.HasOne("InformationSystemsDesign.Models.TypePr", "CdTpNavigation")
                        .WithMany("GLPRs")
                        .HasForeignKey("CdTp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdTpNavigation");
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.Spec", b =>
                {
                    b.HasOne("InformationSystemsDesign.Models.GLPR", "CdKpNavigation")
                        .WithMany("SpecCdKpNavigations")
                        .HasForeignKey("CdKp")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InformationSystemsDesign.Models.GLPR", "CdSbNavigation")
                        .WithMany("SpecCdSbNavigations")
                        .HasForeignKey("CdSb")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CdKpNavigation");

                    b.Navigation("CdSbNavigation");
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.StrRozv", b =>
                {
                    b.HasOne("InformationSystemsDesign.Models.GLPR", "CdKpNavigation")
                        .WithMany("StrRozvCdKpNavigations")
                        .HasForeignKey("CdKp")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InformationSystemsDesign.Models.GLPR", "CdSbNavigation")
                        .WithMany("StrRozvCdSbNavigations")
                        .HasForeignKey("CdSb")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InformationSystemsDesign.Models.GLPR", "CdVyrNavigation")
                        .WithMany("StrRozvCdVyrNavigations")
                        .HasForeignKey("CdVyr")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CdKpNavigation");

                    b.Navigation("CdSbNavigation");

                    b.Navigation("CdVyrNavigation");
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.GLPR", b =>
                {
                    b.Navigation("SpecCdKpNavigations");

                    b.Navigation("SpecCdSbNavigations");

                    b.Navigation("StrRozvCdKpNavigations");

                    b.Navigation("StrRozvCdSbNavigations");

                    b.Navigation("StrRozvCdVyrNavigations");
                });

            modelBuilder.Entity("InformationSystemsDesign.Models.TypePr", b =>
                {
                    b.Navigation("GLPRs");
                });
#pragma warning restore 612, 618
        }
    }
}
